### **Kaggle Titanic_tutorial**



---

In [1]:
import pandas as pd #모듈을 불러올 때 - import

  **CSV = Comma-seperated values**  : excel 포맷보다 훨씬 더 빠르게 데이터를 불러올 수 있음

In [2]:
data = pd.read_csv('http://bit.ly/ld-sample-idol', index_col='순위')
# 다운로드 url을 통한 데이터 읽어오기
# index_col = 인덱스를 이렇게 부르겠다 ~~~

In [3]:
data.head() 
#찐 데이터 불러오기
#table 형태 = dataframe

      이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
순위
1     지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
2   지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
3   강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
4      뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
5     화사    마마무  RBW  여자  1995-07-23  162.0   A   7650928





---

+ 데이터 선택 _ column 열

In [4]:
data ['이름'] 
# 동일한 방법 = data.이름 -> but 가독성 X

순위
1       지민
2     지드래곤
3     강다니엘
4        뷔
5       화사
6       정국
7       민현
8       소연
9        진
10     하성운
11      태연
12     차은우
13      백호
14      JR
15      슈가
Name: 이름, dtype: object

- 데이터 선택 _ row 행

In [5]:
data.iloc[3]
# 1개 [갖고 오고 싶은 행]
# 범위 [:] - 슬라이싱
# 띄엄띄엄 [[,]]

이름                  뷔
그룹              방탄소년단
소속사               빅히트
성별                 남자
생년월일       1995-12-30
키                 178
혈액형                AB
브랜드평판지수       8073501
Name: 4, dtype: object

- 동시 선택

In [6]:
data['그룹'].loc['정국']

KeyError: ignored

In [7]:
data['이름'].iloc[3]
# 먼저 column 선택 -> row 선택
# row 하나씩, 범위, 띄엄띄엄 동일

'뷔'

In [8]:
data.iloc[1,3,5,7,9]

IndexingError: ignored

In [9]:
data.iloc[3:7]

    이름     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
순위
4    뷔  방탄소년단   빅히트  남자  1995-12-30  178.0  AB  8073501
5   화사    마마무   RBW  여자  1995-07-23  162.0   A  7650928
6   정국  방탄소년단   빅히트  남자  1997-09-01  178.0   A  5208335
7   민현   뉴이스트  플레디스  남자  1995-08-09  182.0   O  4989792

In [10]:
select = [1,3,5,7,9]
data.iloc[select]

      이름     그룹      소속사  성별        생년월일      키 혈액형  브랜드평판지수
순위
2   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A  9916947
4      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB  8073501
6     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A  5208335
8     소연    아이들       큐브  여자  1998-08-26  157.0   B  4668615
10   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.0   A  4036489



---

**Pandas 기능**

1. 간단 산술 통계

  - info(): 데이터들의 정보 열람
  - describe(): 데이터의 산술 통계 정보 (산술 가능 = 숫자로 표현 가능)
  - isnull(): 데이터 누락?
  - sum(): 데이터 합산
  - value_ counts: 데이터 종류별 갯수 확인

2. 고급 산술 통계
  - groupby ( = pivot_table): 특정 column 데이터

3. 조건 필터링
  - loc: 조건문에 대한 필터를 걸어 데이터 확인
  - &와 | 연산자: & and , | or

4. 데이터 전처리
  - replace(): 데이터를 다른 값으로 바꿀 때
  - fillna(): 빈 값 채우기 (Na = Not a Number)
  - map(): 데이터 매핑